MAX_GAME_TITLE_LENGTH = 32

DEFAULT_THINK_TIME = 60
MIN_THINK_TIME = 5
MAX_THINK_TIME = 600

DEFAULT_ROUND_END_TIME = 8
MIN_ROUND_END_TIME = 2
MAX_ROUND_END_TIME = 30

DEFAULT_IDLE_ROUNDS = 2
MIN_IDLE_ROUNDS = 1
MAX_IDLE_ROUNDS = 5

DEFAULT_BLANK_CARDS = 0
MAX_BLANK_CARDS = 40

DEFAULT_PLAYER_LIMIT = 10
MAX_PLAYER_LIMIT = 20

DEFAULT_POINT_LIMIT = 8
MAX_POINT_LIMIT = 50

DEFAULT_PASSWORD = ""
MAX_PASSWORD_LENGTH = 100

DISCONNECTED_KICK_TIMER = 120
DISCONNECTED_REMOVE_TIMER = 600

HAND_SIZE = 10

NAME_REGEX = r"^(?!.*(?:^ |  | $))[a-zA-Z0-9_\- ]{3,32}$"
